//
// SentinelHook - IOCTL Definitions
// Common header for kernel driver and user-mode service
//

#pragma once

#include <windows.h>

// Device name and symbolic link
#define SENTINELHOOK_DEVICE_NAME     L"\\Device\\SentinelHook"
#define SENTINELHOOK_SYMBOLIC_LINK   L"\\DosDevices\\SentinelHook"
#define SENTINELHOOK_USER_DEVICE     L"\\\\.\\SentinelHook"

// IOCTL base
#define SENTINELHOOK_IOCTL_BASE      0x8000

// IOCTL codes
#define IOCTL_SENTINELHOOK_GET_TELEMETRY \
    CTL_CODE(FILE_DEVICE_UNKNOWN, SENTINELHOOK_IOCTL_BASE + 0x01, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_SENTINELHOOK_GET_STATS \
    CTL_CODE(FILE_DEVICE_UNKNOWN, SENTINELHOOK_IOCTL_BASE + 0x02, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_SENTINELHOOK_SET_FILTER \
    CTL_CODE(FILE_DEVICE_UNKNOWN, SENTINELHOOK_IOCTL_BASE + 0x03, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_SENTINELHOOK_ENABLE_MONITORING \
    CTL_CODE(FILE_DEVICE_UNKNOWN, SENTINELHOOK_IOCTL_BASE + 0x04, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_SENTINELHOOK_DISABLE_MONITORING \
    CTL_CODE(FILE_DEVICE_UNKNOWN, SENTINELHOOK_IOCTL_BASE + 0x05, METHOD_BUFFERED, FILE_ANY_ACCESS)

// Maximum buffer sizes
#define MAX_TELEMETRY_BUFFER_SIZE    (64 * 1024)  // 64 KB
#define MAX_PATH_LENGTH              260
#define MAX_PROCESS_NAME_LENGTH      256

